### PR TITLE
Activate virtualenv if not before running OWTF

### PR DESCRIPTION
**Pull request by DarKnight24**
Now OWTF can be executed without activating the virtualenv.

## Description

This PR checks whether virtualenv is activated or not, if not then activates it before running OWTF.
 
## Reviewers

@viyatb @DePierre 

## How Has This Been Tested?

By running owtf in different scenarios.
 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DePierre** [comment]
*My comment below might be a rant about OWTF's installation process. If you believe that my arguments are wrong, feel free to ignore me. Right now, I believe that they are justified.*

I see more and more code related to OWTF's installation, which contain hackish calls to system, exec and whatnots. It doesn't make me feel comfortable personally.

I have no experience in installation process but I believe that we reached a point (or reached months, years ago) where we are stepping out of what OWTF should be doing. For instance:

+ The user should decide whether he wants to run OWTF in a virtual environment or not.
+ There is a problem with the user SSL configuration? OWTF should not try to fix it.
+ Kali broke something? OWTF shoud not try to fix it.
+ pip broke something? OWTF should not try to fix it.

OWTF is not supposed to try to fix the user's system or other packages' issues. We already have a lot to fix in our own codebase already IMO. OWTF should provides a clean installation process where it only installs the python PyPi packages it needs, creates the directories it needs and nothing else. Skipfish is not present? Not OWTF's problem to fix. W3AF does not work? Not OWTF's problem to fix. PostgreSQL is not started? Not OWTF's problem.

Is there any one who has experience with installation process and could provide meaningful input? I remember that https://github.com/owtf/owtf/issues/725 (opened by @blshkv) seemed to contain good arguments and recommendations on how the installation process should go. I would like to have an outside point of view about OWTF's current installation process.

I would like to strip all hackish code like the one provided in this PR (nothing personal @DarKnight24) from the OWTF code base. I would agree on creating a new repository containing all hackish code for fixing Kali, starting postgresql, etc. that the user may want to run if he wants to *fix* his Kali distribution.

I know it's old but I remember the time where I could simply `git clone owtf.git && pip install -r install/owtf.pip && python install/install.py` on my Archlinux. And where I did not need to be root!

**Comment by viyatb** [comment]
@DePierre in short, I agree with you. But there are a few considerations:

* re: virtualenv - Kali changed the permissions on the global Python packages directory. You can no longer update/upgrade packages already installed (because they would break the existing bundled tools).
This is the sole reason we need virtual environment for OWTF.
* re: SSL problems - I agree. They were a short term fix and meant to be removed (the release cycle at that time was not rolling, hence they were kept.)
* re: Kali broke - the tools adapt to the environment, otherwise it would be unusable for most users. Some feature might break the functionality for a small subset of tools and that may be a low priority for Kali maintainers to fix. What then?
* re: Pip broke something - again the same thing as above. Usability is the priority here for us.
* re: system scripts: This is why we have separate scripts which help fix these issues in the `scripts/` folder and not the `framework`. However I strongly disagree on decoupling those scripts from the main repository.

Let me know what you think. @7a can you pitch in? :)

**Comment by DePierre** [comment]
@viyatb Thanks for providing some feedback. Just to be more realistic, the current situation about having more and more code related to install/env/dependency inside OWTF's source code is still manageable. However, it seems to get worse so I would rather be alarmist now than hopeless later.

I am surely overreacting.

> - re: virtualenv - Kali changed the permissions on the global Python packages directory. You can no longer update/upgrade packages already installed (because they would break the existing bundled tools).
> This is the sole reason we need virtual environment for OWTF.

I was not aware of this and it makes some sense from Kali's point of view. Do we know how other tools proceed? Are they all moving to virtualenv?

> - re: Kali broke - the tools adapt to the environment, otherwise it would be unusable for most users. Some feature might break the functionality for a small subset of tools and that may be a low priority for Kali maintainers to fix. What then?

If it is Kali's fault, then we do nothing but let the users complain to Kali. If Kali disagrees, then too bad for the users but we can still provide them with links to work-arounds and scripts, **independent** from OWTF normal installation. Which, to be honest, is what we have started to do for a while now (like asking the user if he wanted OWTF to fix the SSL configuration for postgresql, instead of silently patching it for him)

> - re: Pip broke something - again the same thing as above. Usability is the priority here for OWTF.

My position is that OWTF **should not** have to fix other project's bugs. If pip broke something, then it's pip's responsibility to revert their changes or provide the new way to do what we were doing in the past.

We already have the heavy burden of maintaining our list of plugins working (and not all of them are working). And it's a lot to do! My example with w3af might have been misleading in the sense that OWTF **should** keep its w3af configuration up-to-date to work with W3AF's latest version. However, OWTF **should not** try to hot-patch w3af's code to fix a w3af bug.

> - re: system scripts: This is why we have separate scripts which help fix these issues in the scripts/ folder and not the framework. However I strongly disagree on decoupling those scripts from the main repository.

You are right, it's already decoupled if they are in a dedicated directory and I don't mind keeping them there. I might have gone too far with the dedicated repository idea. What I want is to get rid of all the python code inside OWTF's source code that are related to dependency checks, virtualenv checks, etc.

**To rephrase**, the current situation is not as bad as I pictured it. There is indeed a dedicated directory where temporary fixes have been written. However, the trend I am seeing is more and more code inside OWTF that are related to checking installation things (like whether dependencies have been installed or virtualenv has been enabled) that should not be part of the core code.

How could the following code (from the PR) belong to OWTF's code base?

```python
shell_rc_path = os.path.join(os.environ["HOME"], ".%src" % os.environ["SHELL"].split(os.sep)[-1])
dump = '%s -c "import os, json;print json.dumps(dict(os.environ))"' % sys.executable
pipe = subprocess.Popen(['/bin/bash', '-c', 'source %s >/dev/null 2>&1; %s' % (shell_rc_path, dump)], stdout=subprocess.PIPE)
env = json.loads(pipe.stdout.read())
# Update the os environment variable
os.environ.update(env)
```

(Again, nothing personal @DarKnight24. I am pointing out that OWTF embeds more and more snippet like yours that do not belong to OWTF's code base. OWTF is a python framework to provide an easy-way for users to follow pen-testing guides. OWTF should not be a freak of fake python code that is in fact bash code just to do something that we shouldn't)

**Comment by blshkv** [comment]
Guys, 
By looking at your comments I got an impression that you have finally realised that you are getting too far. So far, that eventually your script will be downloading a specific ISO image of kali image first, patching all stuff and acting like your tool is the only tool a user would run (and breaking other tools potentially). This is obvious a wrong path.

You should care less whether user's env it is docker, virtualenv, kali or any other linux distro. 
Please provide a *standard* setup.py (https://docs.python.org/3/install/) and let distro maintainers do their job.

From the other side, owtf *should*:
 - expect that it will be installed in a system directory
 - able to run under regular user's privilege (unless there is a really good reason)
 - pre-install required configuration files in /etc file
 - create ~.owtf/* folders/files during runtime if they are missing (instead of crashing).
 - supervise local configuration files in the local ~./owtf folder
 - redirect all output to that local directory *by default*
 - handle other missing dependencies properly (just display a warning and disable the functionality)
The list can go on.

This is how it works for thousand tools up there.

**Comment by DePierre** [comment]
@blshkv One specificity about OWTF that could justify why we took the wrong decision of focusing on Kali and getting too far is that OWTF relies on 10, 20 even 30 different security tools (tools, not libraries or packages. actual tools that should be used by human users in the first place) and Kali is among the few distributions that provides them pre-installed (others being BlackArch).

It's therefore understandable to couple OWTF and Kali. I agree with you, it's the wrong path, but I thought I could give some insight about why.

**Comment by viyatb** [comment]
@blshkv you are missing the main point: OWTF is the glue for the thousands of tools you mentioned.  Its a framework first and then a tool.

@DePierre I can start removing the cruft from the codebase. I was thinking of creating a branch from develop to rewrite, modify, refactor OWTF inside out.

**Comment by blshkv** [comment]
@viyatb I'm pretty sure I'm not missing anything ;-) owtf is just one of thousands frameworks in my system, however it is trying to patch other frameworks (such as w3af) and modify system files without my permission. I have to rip off these malicious functions from each version of the tool and this is a lot of work.

**Comment by viyatb** [comment]
Closing the PR according to the above discussion.

**Pull request closed without merging**
