### PR TITLE
Fix Set-Cookie header handling in proxy. Fixes #582

### LINKED ISSUE #582: Improper Set-Cookie header handling in proxy
#### Bug

+ Try using owtf proxy to browse to any wordpress admin page.
+ Try logging in. (Invalid credentials will also do)
+ You should see a message on the login page that cookie support seems disabled!!!

#### Fix

[This line](https://github.com/owtf/owtf/blob/4c3ae8182cf4ce0948fd3d876a8eeba1a55d3fc2/framework/http/proxy/proxy.py#L76) 

```
for header, value in list(response.headers.items()):
```

should be

```
for header, value in response.headers.get_all():
```

#### Verification

+ Repeat the same steps and you should see no such cookies disabled message.
+ Do not send a PR or commit without verifying the fix first!!

#### Reasoning

+ Servers send multiple **Set-Cookie** headers
+ When iterated over these headers using items, list of set-cookie header values is joined using comma
+ This format of mentioning multiple cookies in one Set-Cookie header seperated by comma is not recognised by browsers.
+ The ideal way of doing this is by using ``get_all()`` method of tornado headers.

### PR DESCRIPTION
**Pull request by karandesai-96**
Replaces `headers.get_items()` to `headers.get_all()` in **framework/http/proxy/proxy.py** as directed in #582 to overcome the error.

The relevant screenshots:
* Before fixing:
image

* After fixing:
image

### CODE REVIEW

**Comment by ner0x652** [comment]
In the second screenshot, the message says "... or username nvalid..." while the entered username is invalid. Is there some problem with that or am I wrong?

**Comment by karandesai-96** [comment]
Oh that, never mind, I wrote 'nvalid' realized I had a typo so typed an 'i' - making it ready for the photoshoot :smile: When I posted the screenshot, I realized how dumb did I behave haha!

It isn't a bug, it's me :smile:

**Comment by delta24** [comment]
@karandesai-96 What is the status? Is the error still coming in the proxy logs?

**Comment by karandesai-96** [comment]
Yes, I have tried using `enumerate`and `.keys()` too. These too do not give the error in proxy logs but again the cookies are disabled :confused:

**Comment by delta24** [comment]
Paste the complete error here @karandesai-96

**Comment by karandesai-96** [comment]
In case of enumerate, here is the traceback:
```
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1484, in future_complete
        f.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
        yielded = self.gen.send(value)
      File "/home/darth_sidious/Documents/owtf/framework/http/proxy/proxy.py", line 236, in get
        self.finish_response(response)
      File "/home/darth_sidious/Documents/owtf/framework/http/proxy/proxy.py", line 76, in finish_response
        for iterable, header, value in enumerate(response.headers.items()):
    ValueError: need more than 2 values to unpack
```

**Comment by delta24** [comment]
Cookie parsing thing is a separate issue, paste the original `get_all` error.

**Comment by karandesai-96** [comment]
For get_all():
```
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1484, in future_complete
        f.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
        yielded = self.gen.send(value)
      File "/home/darth_sidious/Documents/owtf/framework/http/proxy/proxy.py", line 126, in get
        self.finish_response(self.cached_response)
      File "/home/darth_sidious/Documents/owtf/framework/http/proxy/proxy.py", line 76, in finish_response
        for header, value in response.headers.get_all():
    AttributeError: 'dict' object has no attribute 'get_all'
```

**Comment by tunnelshade** [comment]
@karandesai-96 I understand the error. This is because of the cached responses!!!

#### Fix

Change [this] (https://github.com/owtf/owtf/blob/develop/framework/http/proxy/cache_handler.py#L139) in `cache_handler.py` from

```
dummyResponse.headers = cache_dict["response_headers"]
```

to

```
dummyResponse.headers = tornado.httputil.HTTPHeaders(cache_dict["response_headers"])
```

**PS**: Don't forget to import tornado.httputil in `cache_handler.py`

**Pull request merged**
