### PR TITLE
Moved test_group files to profile folder, fixes #670

### LINKED ISSUE #670: xxx_testgroups.cfg should be moved to /profiles
The different configuration files for [web](https://github.com/owtf/owtf/blob/develop/framework/config/web_testgroups.cfg), [net](https://github.com/owtf/owtf/blob/develop/framework/config/net_testgroups.cfg) and [aux](https://github.com/owtf/owtf/blob/develop/framework/config/aux_testgroups.cfg) groups should be moved to ['/profiles'](https://github.com/owtf/owtf/tree/develop/profiles) as they are plugin configuration files.

The [framework_config.cfg](https://github.com/owtf/owtf/blob/develop/framework/config/framework_config.cfg) configuration file should be updated accordingly.

### PR DESCRIPTION
**Pull request by DarKnight--**
Moved test_group files to profile folder

## Related Issue

fixes #670 

## Motivation and Context

The changes will separate the plugin configuration files from framework.

## Reviewers

@DePierre

## How Has This Been Tested?

`./owtf.py -l auxiliary`, lists successfully the plugins of the `auxiliary` group.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [ ] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by delta24** [comment]
@DarKnight-- Better make that `testgroups` folder (in sync with the filenames `aux_testgroups`)

**Comment by DePierre** [comment]
@delta24 How about moving them in the same folder as ``net_plugin_order``, etc. ?

We could rename the directories to something like:
+ `plugin_web`
    + `plugin_web_order.cfg`
    + `plugin_web_test_groups.cfg`

The same for `aux` and `net`. What do you think?

**Comment by delta24** [comment]
@DePierre sure, nice idea!. Just that the  `plugin_web_order.cfg` should be `web_order.cfg`. :P (repetitive)

**Comment by DePierre** [comment]
Then why not just ``order.cfg`` and ``groups.cfg`` since web would be repetitive as well?
To be honest, I am not even sure why it is named ``testgroups.cfg`` in the first place, do you know @delta24 ?

**Comment by DePierre** [comment]
Trigger Travis.

**Comment by DePierre** [comment]
@DarKnight-- Thank you! :)

**Pull request merged**
