### PR TITLE
Check access rights for OUTPUT_PATH

### PR DESCRIPTION
**Pull request by alexandrasandulescu**
I hardcoded ~/.owtf. Where should this default path be added? default.cfg is not a good idea because users can modify it and we want "~/.owtf" to be the failure solution for bad config.

### CODE REVIEW

**Comment by alexandrasandulescu** [comment]
Plus, I tested it on Arch Linux where the source is copied by pacman to /usr/share/owtf

**Comment by tunnelshade** [comment]
Hardcoding ~/.owtf should ideally be done in `framework/config/framework_config.cfg`

**Comment by alexandrasandulescu** [comment]
@tunnelshade , please check the fix

**Comment by DePierre** [comment]
@alexandrasandulescu Could you please fix the coding style in your pull requests? We are ~~trying~~ to follow the pep8 (exception being 120 limited chars per line (CR included)).
For instance:
+ [This can be onlined](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R56)
+ [This can be onlined](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R526)
+ [This is not C, no need for parenthesis, please remove them](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R525)
+ [This can be onlined](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R529)
+ [Superfluous parenthesis](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R589)
+ [Superfuous parenthesis](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R590)
+ [Comments start with '# ' (notice the space after the hash) and upper case on the first letter, and finish with a period '.'](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R593)
+ [Superfluous parenthesis](https://github.com/owtf/owtf/pull/486/files#diff-9700eadd491a8f09de8d45e234631ef1R594)
+ [This can be onlined](https://github.com/owtf/owtf/pull/486/files#diff-073dcc3a79a4c73949d629a610e5e6bdR66)
+ [Documentation on the function?](https://github.com/owtf/owtf/pull/486/files#diff-073dcc3a79a4c73949d629a610e5e6bdR63)

PEP8:
+ [Maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) (s/79/119 for OWTF)
+ [Comments](https://www.python.org/dev/peps/pep-0008/#comments)
+ [Recommendations](https://www.python.org/dev/peps/pep-0008/#programming-recommendations)

PEP257:
+ [Docstrings](https://www.python.org/dev/peps/pep-0257/)

Sphinx:
+ [Sphinx docstring examples](https://pythonhosted.org/an_example_pypi_project/sphinx.html)

**Comment by alexandrasandulescu** [comment]
@DePierre thanks. I'll keep that in mind . fixed

**Comment by delta24** [comment]
@tao: Sphinx syntax has not been written for the majority part of OWTF - isn't just the docstrings sufficient for this case?

**Comment by DePierre** [comment]
@delta24 Your comment makes me so sad...

I am trying my best since almost 2 years to push pep8 code with sphinx-like docstrings step by step for any new code I am adding to the codebase. If anyone would do the same day after day, the codebase would be easier to read. Instead, it is just unbearable, nobody understands anything, no doc, no coding rules, nothing.

Please reconsider writing PEP8 code with Sphinx docstrings for, at least, **any new added code**.

**Comment by delta24** [comment]
Don't get me wrong. Sphinx-like docstring comments are invaluable for any code. But the as a practice, I think either the whole module/ or the whole `.py` file should have them, not only the newly added code. If @alexandrasandulescu is ready to add the docstring comments for the whole module, well and good!
Cheers!

**Comment by DePierre** [comment]
No one will ever write documentation for OWTF at once but going step by step makes everything possible.
Sure it would be nice to have sphinx docs for all functions but are you ready to do that? I don't think so.
This is childish to use the "yes but no one else does so why should I do that?"
Also, this is a requirement for OSCS
https://www.owasp.org/index.php/Summer_Code_Sprint2015#OWASP_OWTF_-_HTTP_Request_Translator_Improvements
Check the Expected Results

**Comment by tunnelshade** [comment]
Okay guys, @delta24 It is good to have docstrings for the whole module but as @DePierre says it cannot be done overnight. Once we start writing it for the new code that we write we will get accustomed to it and subsequently will be useful.

@alexandrasandulescu Use a PEP8 checker with your IDE/Editor to follow PEP-8

**Comment by alexandrasandulescu** [comment]
@tunnelshade , fixed

**Pull request merged**
