### PR TITLE
Progress Bar for Scan created. Fixes #373

### LINKED ISSUE #373: Show progress of scan
On the Workers page, show progress with the total number of plug-ins selected and the number of the plug-in that is currently running.

For example:  (12/50)
Running the 12th plug-in of the 50 that were selected.

### PR DESCRIPTION
**Pull request by saganshul**
@delta24 @7a @DePierre  Please review. Fixes #373

### CODE REVIEW

**Comment by delta24** [comment]
Can you provide a screenshot?

**Comment by saganshul** [comment]
screenshot from 2016-03-12 07-26-15
screenshot from 2016-03-12 07-26-17

**Comment by delta24** [comment]
OK, so the reason we want the progress bar is to reduce the number of clicks+time needed to see which plugins are left.

Can you modify the homepage (/) to have a nice overview of the scans  running (pretty UI thing)? Also it would be great if you can show the plugin currently running near the progress bar.

**Comment by saganshul** [comment]
@delta24 , sure I will do that. So progress bar should be on / or /ui/worker or both. If you want only on homepage, then I will remove it from /ui/worker. Also I will show the currently running plugin near progress bar.

**Comment by DePierre** [comment]
@saganshul are you sure you wanted to close that PR? And not continue working on the issue here? Just asking.

**Comment by saganshul** [comment]
@DePierre  This PR doesn't have any problem but @delta24  told me that in spite of having progress on workers page it should be on home page so I closed the PR because of some issue with my next PR. I will soon give new PR which will have progress bar on homepage. If you want progress bar on  workers page then please review and if it doesn't have any problem you can merge it.

**Pull request closed without merging**
