### PR TITLE
Debian Installer Scripts

### PR DESCRIPTION
**Pull request by C0smos**
I've added the ability to install OWTF on Debian

### CODE REVIEW

**Comment by tunnelshade** [comment]
You have committed lots of extra files. Please clean up.

**Comment by C0smos** [comment]
Removed the extra files

**Comment by DePierre** [comment]
@C0smos Could you please clean your commits history? I see commits named "Adding timestamps to transaction logger" even though it has no link with your PR.

Also, anyone with debian in their hands to test the PR?

**Comment by C0smos** [comment]
Sorry, those commits were changes that hadn't been properly implemented or tested yet so I removed them which is why there's no link. I'll remove the out of date commit message now. Apologies for this.

**Comment by DePierre** [comment]
New PR #483

**Pull request closed without merging**
