### PR TITLE
[webui] Removes recently finished targets polling to improve preformance

### PR DESCRIPTION
**Pull request by saganshul**
Removes recently finished targets polling to improve performance

## Description
This is done because polling this endpoint is not much of importance and also it keeps server busy and hence decreases the performance.

## Reviewers
@delta24 @7a 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### CODE REVIEW

**Comment by delta24** [comment]
@saganshul if you removed the polling, then the feature is not useful anymore, right? Then it would be better to remove it.

**Comment by saganshul** [comment]
@delta24 well I think it will still be useful because recently finished will be present on page load. Other than this what we can do we can increase the timeout period like 5 min or something?

**Comment by delta24** [comment]
@saganshul IMO a better approach would be:
- remove the existing implementation for this
- Make a new notifications center and push all error messages, scan completion messages, etc there

This should use websockets for better performance and low overhead.

**Comment by saganshul** [comment]
@delta24 that approach will be best. I think we should create issue regarding this as new feature and will work on it.

**Pull request merged**
