### PR TITLE
[webui] Transaction log created

### PR DESCRIPTION
**Pull request by saganshul**
This PR creates a new navigation tab, Transactions. 

## Reviewers
@delta24 @tunnelshade @7a @anantshri 

## How Has This Been Tested?
This is tested on chrome and firefox browsers

## Screenshots (if appropriate):
screenshot from 2016-07-06 21-57-20
screenshot from 2016-07-06 21-57-14
screenshot from 2016-07-06 21-57-12
screenshot from 2016-07-06 21-57-09
screenshot from 2016-07-06 21-56-39
screenshot from 2016-07-06 21-56-33
screenshot from 2016-07-06 21-56-15
screenshot from 2016-07-06 21-56-07
screenshot from 2016-07-06 21-56-05
screenshot from 2016-07-06 21-56-01
screenshot from 2016-07-06 21-55-57
screenshot from 2016-07-06 21-55-56
screenshot from 2016-07-06 21-55-51
screenshot from 2016-07-06 21-55-48
screenshot from 2016-07-06 21-55-44

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### CODE REVIEW

**Comment by saganshul** [comment]
Please find attached screenshots for new interface.

screenshot from 2016-07-11 02-08-39
screenshot from 2016-07-11 02-08-36
screenshot from 2016-07-11 02-08-31
screenshot from 2016-07-11 02-08-27
screenshot from 2016-07-11 02-08-23

**Comment by delta24** [comment]
@saganshul Looks like the material colors are still there.

A few bugs:
- When I select a transaction, ideally it should be highlighted in the table.
- Remove "Transactions" and "Headers and Body" headings - more space.
- More even more space, change the large buttons to smaller tabs
- The resizing of the table is awesome. It would be even better if the resizing option is there for the target list on the left side.

**Comment by saganshul** [comment]
@delta24 Got it. Will solve this bugs as soon as possible.

**Comment by saganshul** [comment]
@delta24, on your third point, I noticed that normal bootstrap tab 
3ea661b1e5c787b002bfcb3a26db7f84
is of same height as of this present tab so there will not be any space improvement if I change them.

**Comment by delta24** [comment]
@saganshul But still looks cleaner and much more "Bootstrappy" with our current interface.

**Comment by delta24** [comment]
@saganshul 

- Looks like you forgot to remove the material UI
- Remove the animation effect on the request, response tab.
- The horizontal resizing is buggy - http://imgur.com/gPMe8yn.

**Comment by saganshul** [comment]
@delta24 , Do you want to remove material UI? Why? It can help in developing the tool UI very much in future. In present implementation there is lot of things working due to material UI like table. In react, material UI makes the Code cleaner and better UI. If I use bootstrap there will be very lot of code problems and If I use https://react-bootstrap.github.io/ this, this is under development. We can't use normal bootstrap CSS with react because code will become very messy and that's why I have included the material UI in project. It can help a lot in improving the tool UI. IMO, material UI should be there in project if we are working in reactJS.

**Pull request merged**
