### PR TITLE
Revert "Added sudo access and corrected update command"

### PR DESCRIPTION
**Pull request by DePierre**
Test travis build (see #807)

### CODE REVIEW

**Comment by DePierre** [comment]
@delta24 @DarKnight24 so reverting ad02c7bfd9b27f372aa13e6d95e93932496a85f9 leads to two interesting results:

+ Travis build takes almost 40 minutes
+ Travis build never ends

I will see how it goes when reverting https://github.com/owtf/owtf/pull/800.

By the way, I am not sure to understand why you break Travis, continue pushing untested commits and merging untested PR, and then just move along, hoping that I would fix it. OWTF has had many stability issues and I thought that it was part of OWTF's priority to become more stable now.

Isn't it a priority anymore?

**Comment by DePierre** [comment]
I am aware that the test suites have bugs and issues due to OWTF not properly releasing resources and because I made mistakes that I haven't found and fixed yet. And I will be happy to fix those issues if one can point them to me.

However, breaking other's people commits because they don't care about breaking the test suites is another thing.

**Comment by DePierre** [comment]
@delta24 @DarKnight24 I fixed the travis configuration to copy the user-specified configuration to the right place (I copied them to their default place but then realized that 6c1ff855773914919f9c3dc3d213bdf0dce16ab4 was copying the default configuration to the user's configuration file).

@delta24 6c1ff855773914919f9c3dc3d213bdf0dce16ab4 is not correct IMO. By default, the configuration files should be loaded from the user's owtf directory if they exist. If not, then OWTF should fallback on the default configuration. With 6c1ff855773914919f9c3dc3d213bdf0dce16ab4, OWTF will assign the default configuration to the user's owtf directory despite the fact that the user didn't ask for it. What do you think? Maybe I am misunderstanding the logic.

**Comment by delta24** [comment]
@DePierre When the user first installs OWTF, the default configuration is copied to `~/.owtf` directory. Then if the user wishes to make any configuration changes,  the user can directly do that without messing up the parent OWTF directory. This serves 2 purposes:
- We keep the repository clean of configuration files
- If in the future we want to package OWTF for different distros/package managers, it becomes a lot easier if the configuration files live outside the repository (by default).

**Comment by DePierre** [comment]
@delta24 Fair point. Based on https://github.com/owtf/owtf/pull/800, I remembered that the default configuration files would not be copied by default but re-reading the thread, I realized that I remembered wrong.

**Comment by DarKnight24** [comment]
@delta24 @Depierre IMO it makes no sense to keep wrong code in the codebase. I think we should comment those command instead of reverting the commit.

**Comment by delta24** [comment]
@DarKnight24 you mean remove instead of commenting, right?

**Comment by DarKnight24** [comment]
@delta24 @DePierre We should remove the code add proper comment to fix the problem of installing package from kali source in future.

The debian script is currently not installing any package which are absent in debian repo.
One of the problem is travis is running on Ubuntu 12.04 and packages from kali requires newer version which are not conflicting with 12.04 version. I recommend to update it to 16.04 using docker. This will help me in correcting the debian script to install all the required packages.
IMO we should also add kali to travis testing.

**Comment by delta24** [comment]
@DarKnight24 Ok, got your point. Btw Travis does not support Kali Linux (only Debian, Ubuntu). Look at the commits in this PR - atm Travis build is passing. 

@DePierre should we just remove the code responsible for this and add a #TODO to fix it if a clean solution is possible?

**Comment by DePierre** [comment]
@delta24 To be honest no idea since I still don't understand what it is supposed to be doing. You and @DarKnight24 are better suited to know what we should do.

+ If Travis fails because it's a problem with the the test suites, I'll be happy to troubleshoot the issue with you and attempt to fix it.
+ If Travis fails because it doesn't support what we are trying to do, then we're screwed. But we could maybe update the test suites to use another tool than skipfish for instance.
+ If Travis fails because the commit broke something, then the commit should first and foremost reverted. Then a PR should be created to discuss why the commit is breaking, if it's expected, how we can fix it, etc.

You want me to rebase the PR on what? It was based on the develop HEAD when I created it so I am not sure to understand what you mean. Basically all I did was revert the commit that was messing with Skipfish installation and updated .travis configuration file to copy the lightweight OWTF configuration files to their new locations (lightweight in a sense that only a subset of plugins will be run, not all of them, to limit the time required to run all the tests).

Let me know.

**Comment by delta24** [comment]
@DePierre the rebase thing was for @DarKnight24 's PR for fixing the said install script.

**Comment by DarKnight24** [comment]
@delta24 @DePierre I have tried to install owtf on Ubuntu 16.04 (Look here) and found that install script runs successfully and installs kali packages too :). 
I had tried to run test on which travis was failing previously also ran successfully.

I think we should configure travis to run Ubuntu 16.04 using docker.

**Comment by delta24** [comment]
@DarKnight24 I don't think we can configure how Travis runs - they actually run the builds on a Ubuntu Docker container.

**Comment by delta24** [comment]
@DePierre should I merge this? I need to merge @DarKnight24 's changes for the install script but I'd prefer if the Travis is actually working first and see what it tells us.

**Comment by DePierre** [comment]
@delta24 I dont know :s After reading through the thread again, I am not sure to understand what's up.

@DarKnight24 If I understood correctly, your commit is good and is working as expected on Kali. But it doesn't work on Ubuntu.
And if I understood correctly, we cannot modify Travis to use something else than Ubuntu.
Is that correct?

So should I update the tests to not use Skipfish? Or should we try to find another solution?

**Comment by delta24** [comment]
@DePierre I mean that we merge this commit as it restores Travis to a working condition. Then I can rerun Travis on @DarKnight24 's PR to make sure it does not break again.

**Comment by DePierre** [comment]
@delta24 sure! I think that it would be wise to have Travis working again so that commits and PRs are at least tested once.

Then we can take time to continue discussing this issue and find the right solution.

**Pull request merged**
