### PR TITLE
Proper Fixes for issue #556

### PR DESCRIPTION
**Pull request by DoomTaper**
Its working properly now!

### CODE REVIEW

**Comment by delta24** [comment]
Tested - works ok now. @DePierre test once? :P

**Comment by delta24** [comment]
Why is there an extra `[-]` in each category? 
https://gist.github.com/delta24/bc61bdf5a39fdd2ae87e

**Comment by DoomTaper** [comment]
If I write `logging.info("message")` then output will be 
`[-] message`
but If I write `logging.info("\nmessage")` then output will be 
`[-] `
`message`
Similar case is happening above. Take a look [here](https://github.com/owtf/owtf/blob/develop/framework/plugin/plugin_handler.py#L476)
I hope you get it @delta24

**Comment by delta24** [comment]
Ah, ok - I thought there was an empty entry from the file being parsed.

**Comment by DePierre** [comment]
@DoomTaper Awesome thanks :)

**Comment by DoomTaper** [comment]
My job!

**Pull request merged**
