### PR TITLE
Login and Forgot password module

### PR DESCRIPTION
**Pull request by amanpro30**
## Description
Contains the various modules required for login of the user and forgot password (setting a new password). Login component hits the backend API for login, gets a JWT token, and stores in the local storage on the client-side (All state managements are also handled accordingly). Forgot Password handles input validations required, sends the OTP, and only verified users can then change their password.

## Reviewers
@viyatb @sharmamohit123 @7a @saganshul @Ashrith-Shetty 

## Screenshots (if appropriate):
image
image
image
image
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sharmamohit123** [comment]
@amanpro30 I am facing an issue while testing the workflow. While signing up I am not getting the verification link due to some reason (resend also not working) and if I try to signup again it says that the user already exists but I am unable to login since the account didn't got activated. Can you pls double-check this?

**Comment by viyatb** [comment]
can you rebase?

**Comment by viyatb** [comment]
@amanpro30 what is the Deepsource thing that keeps committing and appears in your commit messages? Is it possible to remove that on your end?

**Comment by amanpro30** [comment]
> @amanpro30 what is the Deepsource thing that keeps committing and appears in your commit messages? Is it possible to remove that on your end?

Actually, I tried using Deepsource for code review and static analysis in my fork and was playing with it. I deactivated this particular repo from the server and this file won't appear in the latest PRs.

**Pull request merged**
