### PR TITLE
fixed rare wget issue

### LINKED ISSUE #592: Connection reset by peer - wget
**Problem :**
When behind a firewall, (or a proxy that allows only certain user-agents), wget returns a `Connection reset by peer` error. I am currently behind a Sonicwall Firewall and the installation script failed to download most of the stuff. 

**Reason:**
This happens because the Firewall/Proxy blocks certain user agents from making connections. This can cause issues with the installation as the script continues to execute without actually installing the packages.

**Solution:**

Passing a `--user-agent` flag to wget can help tackle the problem. This way, the requests will look as if coming from a browser.

### PR DESCRIPTION
**Pull request by sachinkamath**
Fixes #592 . Tested on a restricted network.

### CODE REVIEW

**Comment by sachinkamath** [comment]
@delta24 @DePierre Please review

**Comment by delta24** [comment]
Is this really necessary? @DePierre

**Comment by sachinkamath** [comment]
@delta24 I'm sure a lot of academic institutions will have such firewalls enabled. Having te `--user-agent` enabled will not break anything (I am using the default user-agent used by OWTF) Also, this will also help a lot of people setting up OWTF in a restricted environment.

**Comment by delta24** [comment]
A better fix IMO will be:

- [ ] rename the colors.sh to utils.sh (take care not to break anything here)
- [ ] add the user agent there (centralised)
- [ ] use `$user_agent` everywhere to keep it simple and clean (KISS)

**Comment by sachinkamath** [comment]
@delta24 Commits added. Please review :)

**Comment by sachinkamath** [comment]
Should work now @delta24 :)

**Comment by delta24** [comment]
Thank you @sachinkamath for the fix!

**Comment by sachinkamath** [comment]
@delta24 Welcome :dancer:

**Pull request merged**
