### PR TITLE
Update Dockerfile to use git repository

### PR DESCRIPTION
**Pull request by rahulsurwade08**
I have updated the dockerfile to use owtf git clone.
## Description

I have replace local copy with git clone. this will remove dependency with local copy of owtf git repository
## Motivation and Context

This change is required to be used for kubernetes deployment of OWTF project.
## Reviewers

@7a @viyatb 
## How Has This Been Tested?

This changes has been tested on local machine
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by viyatb** [comment]
@rahulsurwade08 why replace the local to git clone? The reason for the local clone is to test the changes in a Docker container - not everyone is on a Linux system and allowing them to test changes via local is the way to go. The only time to do a git clone is when you want to push a new image to the registry or when you are trying to use OWTF for the first time.

**Comment by rahulsurwade08** [comment]
@viyatb This changes is required for Kubernetes deployment. I have created kaniko job to build the docker image in the k8s cluster. This change will reduce a step to manually build image in the local and push to docker hub to be used in deployment. Kaniko job will create the docker image and push to docker registry as well. Please let me know if this process suits for our use case.

**Comment by viyatb** [comment]
@rahulsurwade08 can you create a separate dockerfile for this? Put this change in `infra/kubernetes/Dockerfile`. Ideally you want the Docker image for deployment and local dev/testing to be different.

**Comment by viyatb** [comment]
@rahulsurwade08 any update?

**Comment by rahulsurwade08** [comment]
@viyatb I have made the requested changes. Please check. Also by the end of this week, I will raise the PR for Kubernetes manifests. Terraform scripts should be completed by this weekend.

**Comment by viyatb** [comment]
@rahulsurwade08 instead of using the playbook.yml, can you re-use the https://github.com/owtf/owtf/blob/develop/scripts/install.sh in Ansible? https://docs.ansible.com/ansible/latest/collections/ansible/builtin/script_module.html#examples

**Pull request merged**
