### PR TITLE
Fix issue when target url contains reserved characters

### PR DESCRIPTION
**Pull request by csk**
Fix issue when target url contains reserved characters (like questionmark)

## Description

There is an issue with the fileserver and the encoding when a target contains special characters. E.g: http://192.168.0.14/mutillidae/index.php?page=user-info.php

This tiny commit fixes it :)

### CODE REVIEW

**Comment by viyatb** [comment]
@csk the PR looks good. I'll merge after testing this later today.

**Comment by viyatb** [comment]
@csk did you test it? I cannot replicate the fix.

**Comment by csk** [comment]
Yes i did! The problem is that if the target contains reserved characters, the plugin output files are stored in a directory named as by the url.

screen shot 2017-08-01 at 1 36 02 am

The link generated by the reported, if nos correctly escaped, is rendered like:

screen shot 2017-08-01 at 1 33 14 am

The link in the screenshot above is handled by the browser as a url with query params if not escaped correctly and the webserver receives the request and redirects wrongly to an unexistant resource:

screen shot 2017-08-01 at 1 40 21 am

**Comment by viyatb** [comment]
@csk I meant the fix is incorrect. You need to modify `includes/src/Report/Table.jsx` here https://github.com/owtf/owtf/blob/develop/includes/src/Report/Table.jsx#L59.
The fix is `encodeURIComponent(obj['output_path'])`

**Comment by csk** [comment]
I got it! Totally agree with you, the path should not be encoded until displaying it on the web as link. I will fix it and PR.

**Comment by csk** [comment]
@viyatb i just found out that there is non-React stuff which is rendered server side which is also affected.

https://github.com/owtf/owtf/blob/master/framework/interface/templates/poutput/command_dump.html#L8 and https://github.com/owtf/owtf/blob/master/framework/interface/templates/poutput/command_dump.html#L19

Maybe we could pass a uriEncodedFilePath to the template. Do you agree?

**Comment by viyatb** [comment]
@csk how is that affected on the UI? I don't see the point of encoding this in the template. These are being deprecated.

**Pull request merged**
