### PR TITLE
Global severity coloring

### PR DESCRIPTION
**Pull request by saganshul**
As suggested by @7a , This PR globally apply colors for severity.
Colors are as follow:
"not ranked" = gray, "passing" = light green?, "info" = dark green?, "low" = blue, medium = yellow, high = red, critical = dark purple

## Reviewers
@delta24 @7a 

## Screenshots (if appropriate):
screenshot from 2016-09-11 13-13-23
screenshot from 2016-09-11 13-13-08

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

### CODE REVIEW

**Comment by delta24** [comment]
I'm not sure about "passing" = light green?, "info" = dark green.

**Comment by saganshul** [comment]
@delta24 Please suggest some color. Me and @abe was also not much sure about it.

**Comment by delta24** [comment]
Maybe http://colors.findthedata.com/l/402/Sky-Blue color for the info findings?

**Comment by saganshul** [comment]
@delta24 then for low?

**Comment by delta24** [comment]
Maybe for info - a very light sky blue color then?

**Comment by saganshul** [comment]
@delta24 Can you please check with @7a ?Because these colors were suggested by him.

**Comment by saganshul** [comment]
@delta24 Info color changed to color #b1d9f4. Please review.

**Pull request merged**
