### PR TITLE
Fix #446: Improve Curl PUT test command output

### LINKED ISSUE #446: Improve curl commands
@7a : 
We need to improve CLI commands for ease of manual verification, for example, the curl PUT test, needs to be arranged so that it’s easy to verify “what was even attempted to be uploaded”, for example:

```bash
FILE=$(head /dev/random -c8 | od -tx1 -w16 | head -n1 | cut -d' ' -f2- | tr -d ' '); echo "Tried File: $FILE"; curl -s -i -A 'Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0' -X 'PUT' --data "$FILE" -k "https://target.com/admin/$FILE"
Tried File: 44b7fa5e6d0d5798
```
ie. right now, we are calling /dev/random twice so that's not repeatable. The whole point of the curl commands is to give something repeatable so that the tester can copy + paste to see if the same response comes up.

### PR DESCRIPTION
**Pull request by arunk-s**

### CODE REVIEW

**Comment by DePierre** [comment]
@delta24 Could you have a look?

**Comment by delta24** [comment]
@arunk-s Can you check the other `curl` commands in the `profiles/resources/default.cfg`?

**Comment by arunk-s** [comment]
@delta24 Checked the other curl commands in the file. I've found that all of them should be easily repeatable as they involve (`OPTIONS, TRACE, DEBUG,`) checks. Also I've noticed that they all redirect `stderr` to `/dev/null` which is probably a good thing.

**Comment by delta24** [comment]
Same as https://github.com/owtf/owtf/pull/600. Closing.

**Pull request closed without merging**
