### PR TITLE
Remove 'tests' and link 'owtf_testing' repo to owtf's repo.

### PR DESCRIPTION
**Pull request by karandesai-96**
This PR is in continuation to the vision of #598.
According to what was decided in the last comment there, **tests** directory was obsolete hence removed, and @DePierre 's [owtf_testing](https://www.github.com/DePierre/owtf_testing) has been brought in and made a part of this repo.

### CODE REVIEW

**Comment by DePierre** [comment]
@karandesai-96 Where you able to successfuly run the tests? For instance the 'fast' test suite against OWTF?

**Comment by karandesai-96** [comment]
It throws ImportErrors due to circular imports. I am working on another PR - will get back to this once it is done there.

**Comment by delta24** [comment]
Fixed the errors? @karandesai-96

**Comment by delta24** [comment]
Closing this PR for the time being as there are many errors to fix in owtf-testing (circular imports, etc),

**Comment by karandesai-96** [comment]
Yes well enough. I will get back to it sometime around May.

**Pull request closed without merging**
