### PR TITLE
Fixed issue in path of plugin groups

### PR DESCRIPTION
**Pull request by DarKnight24**
This bug was introduced in [this](https://github.com/owtf/owtf/commit/6c1ff855773914919f9c3dc3d213bdf0dce16ab4) commit.

### Current Behaviour:
If any configuration file is missing in `~/.owtf/` folder then current owtf expects it to be strictly in `@@@RootDir@@@/configuration/`. As the default plugin config files are in `@@@RootDir@@@/configuration/profiles/`, this makes default files unavailable.

### Expected Behaviour:
The path of the config files should be stored in the framework config file and the function returning the path of config file must not have path hard coded.

This PR fixes the error in default path extraction. When default path is calculated it expects default file path relative to @@@RootDir@@@/configuration.

### CODE REVIEW

**Comment by delta24** [comment]
@DarKnight24 I specifically wanted to keep the profiles directory separate.

**Comment by DePierre** [comment]
@DarKnight24 Please update the Travis configuration file accordingly

**Comment by DarKnight24** [comment]
@viyatb I will update this pr by shifting hard coded paths to config file.

**Comment by viyatb** [comment]
@DarKnight24 can you elaborate more on the bug, why and what in the description? It would be useful for future reference.
Btw the changes LGTM.

**Comment by DarKnight24** [comment]
@viyatb I have updated the description.

**Pull request merged**
