### PR TITLE
New vulnerability search resources

### PR DESCRIPTION
**Pull request by gameFace22**
The committed change adds us an extra feature which allows us to search for CVE details for any product+vendor.
Using passive google search.

### CODE REVIEW

**Comment by DePierre** [comment]
@tunnelshade Is this still accurate to the current version of OWTF?

**Comment by tunnelshade** [comment]
Yes, it is. But it has to be verified before merging

**Comment by gameFace22** [comment]
Hey.
Just thought of informing you guys before giving a pull.

**Comment by marioskourtesis** [comment]
Thnx gameFace22, I am on it to test your commit.

**Comment by gameFace22** [comment]
Thank you ;)

**Pull request merged**
