### PR TITLE
Added 3 Httprint Signatures

### PR DESCRIPTION
**Pull request by RahulPratapSingh**
Added 3 Httprint Signatures:

-Apache/2.4.9 (Win32) PHP/5.5.12
-TornadoServer/4.0.2
-Apache/2.4.18 (Debian)

### CODE REVIEW

**Comment by delta24** [comment]
How did you generated those signatures? @RahulPratapSingh

**Comment by RahulPratapSingh** [comment]
@delta24 By running Httprint against the server, in lab. These signatures were not in the signatures list of Httprint as well as signatures list in OWASP OWTF.

**Comment by delta24** [comment]
Thank you @RahulPratapSingh - make sure you contact the guys over at NetSpark and submit your new signatures.

**Comment by RahulPratapSingh** [comment]
You're welcome :) Sure, I will drop a mail to them with signatures. 
I guess, Httprint belongs to net-square. ;)

**Pull request merged**
