### PR TITLE
[virtualenv] Force check for Python virtualenv before any OWTF imports

### PR DESCRIPTION
**Pull request by viyatb**
This PR forces OWTF to check if the Python virtualenv is activated before importing any OWTF modules in the main script.

cc: @DePierre @7a @DarKnight24 feedback please! :)

### CODE REVIEW

**Comment by DarKnight24** [comment]
@viyatb Have a look at [this](http://jelly.codes/articles/python-virtualenv-from-within-python/).

**Comment by DePierre** [comment]
@viyatb The code looks fine to me :) (I haven't tested it though)

Quick suggestion: Could we move all code related to dependency check/version check/platform check to `__init__.py`? That would reduce the noise in `owtf.py` and other owtf files IMO.

**Comment by viyatb** [comment]
@DePierre yes, good idea.
@DarKnight24  did you mean that we can use the virtualenv API in `install/install.py`?

**Comment by DarKnight24** [comment]
@viyatb Yes

**Comment by viyatb** [comment]
@DarKnight24 does it have any limitations?

**Comment by DarKnight24** [comment]
@viyatb No, we simply need to run `execfile(os.path.join(venv_dir, "bin", "activate_this.py"))` before importing any dependencies which are installed in virtualenv.

**Pull request closed without merging**
